# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
    ]
